### PR TITLE
Invite UI component for Chat

### PR DESCRIPTION
**Pull request by gtalha07**
PR includes: 
1. Fixed an bottom overflowing issue if you open keyboard when the room has empty messages.
2. Added Invite UI component for chat list.

What's left:

- [x] Add Invite component for the room if the user taps on invited room.

### CODE REVIEW

**Comment by gtalha07** [comment]
Screenshot (51)

**Comment by gtalha07** [comment]
Screenshot_1656066079

**Review by bitfriend — APPROVED** [review]
Great work.
I found you placed `InviteInfoWidget` in both `ChatList` and `ChatScreen`.
Someday we may need to keep it anywhere as global.

**Comment by gtalha07** [comment]
Do not merge it now. I will perform some localization changes.

**Review by bitfriend — APPROVED** [review]

**Comment by gnunicorn** [comment]
@gtalha07 is this ready for merging now?

**Comment by gtalha07** [comment]
> @gtalha07 is this ready for merging now?

Yes will merge it now.

**Pull request merged**
