### PR TITLE
fix verification sheet layout

### PR DESCRIPTION
**Pull request by gtalha07**
- [x]  Fixed the verification emoji appearance in desktop version.

### CODE REVIEW

**Review by bitfriend — APPROVED** [review]
Just tested.
Nice layout.

**Comment by gtalha07** [comment]
> Just tested. Nice layout. I found desktop shows emoji letters in a line. As we know, mobile shows emoji letters in 2 lines.

Yeah actually on desktop it could show in 2 lines but due to ```GridView``` being scrollable it appeared like it only shows the first line. Whereas you could actually scroll to see other line. This is confusing user-wise so I put all of them on one line.

**Comment by gtalha07** [comment]
Also adding flexible doesn't throws overflow errors while resizing the app (unless at a point just breaks the whole UI), so I guess its good enough.

**Comment by bitfriend** [comment]
Cool

**Pull request merged**
