### PR TITLE
Issue130 realtime chat message updates.

### PR DESCRIPTION
**Pull request by gtalha07**
This PR includes fixes to real-time message updates both on Chat List and Chat Screen.

### CODE REVIEW

**Review by bitfriend — APPROVED** [review]
Great work

**Comment by sachintha-s** [comment]
Great, **One improvement:** when the app receives a message it should move to the top of the chat list with respect to the time when the message was sent.

**Comment by gtalha07** [comment]
> Great, **One improvement:** when the app receives a message it should move to the top of the chat list with respect to the time when the message was sent.

I think we should implement this sorting and comparing date time objects in seperate PR, what do you think? @sachintha-s

**Comment by sachintha-s** [comment]
> > Great, **One improvement:** when the app receives a message it should move to the top of the chat list with respect to the time when the message was sent.
> 
> I think we should implement this sorting and comparing date time objects in seperate PR, what do you think? @sachintha-s

Ok, Let's do it in separate PR. now I will approve this.

**Review by sachintha-s — APPROVED** [review]

**Pull request merged**
