### PR TITLE
Issue 65 & UI overflow fix

### PR DESCRIPTION
**Pull request by inderjeet-developer7**
Added adaptive icons with white background as per https://github.com/effektio/effektio/issues/65 requirement, Screenshot below 

processed-3198e421-31ce-4bd6-be29-734f21ed1ae6_Mdm6dRLx
 
Also fix an issue where widget was overflowing : 

- Before : 
image_2022_08_01T05_31_01_898Z

- After : 
processed-8dcdee46-d438-4899-b7e5-5c8a0d5e37a7_gLQD3v1b

### CODE REVIEW

**Comment by gtalha07** [comment]
Thanks for the fixes. Although it's still cause overflow in some devices i.e. Tested on Nexus S
Screenshot_1659371534

**Comment by gtalha07** [comment]
> Thanks for the fixes. Although it's still cause overflow in some devices i.e. Tested on Nexus S Screenshot_1659371534

Please test this with orientations too.

**Review by gtalha07 — APPROVED** [review]
Looks great!

**Comment by gnunicorn** [comment]
@inderjeet-developer7 please resolved the merge conflict and merge this :)

**Pull request merged**
